//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChickenSoftware.Cdyne {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSResponse", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CancelledField;
        
        private System.Guid MessageIDField;
        
        private bool QueuedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        private ChickenSoftware.Cdyne.SMSErrors SMSErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.SMSIncomingMessage[] SMSIncomingMessagesField;
        
        private bool SentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SentDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancelled {
            get {
                return this.CancelledField;
            }
            set {
                if ((this.CancelledField.Equals(value) != true)) {
                    this.CancelledField = value;
                    this.RaisePropertyChanged("Cancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((this.MessageIDField.Equals(value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Queued {
            get {
                return this.QueuedField;
            }
            set {
                if ((this.QueuedField.Equals(value) != true)) {
                    this.QueuedField = value;
                    this.RaisePropertyChanged("Queued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ChickenSoftware.Cdyne.SMSErrors SMSError {
            get {
                return this.SMSErrorField;
            }
            set {
                if ((this.SMSErrorField.Equals(value) != true)) {
                    this.SMSErrorField = value;
                    this.RaisePropertyChanged("SMSError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.SMSIncomingMessage[] SMSIncomingMessages {
            get {
                return this.SMSIncomingMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSIncomingMessagesField, value) != true)) {
                    this.SMSIncomingMessagesField = value;
                    this.RaisePropertyChanged("SMSIncomingMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Sent {
            get {
                return this.SentField;
            }
            set {
                if ((this.SentField.Equals(value) != true)) {
                    this.SentField = value;
                    this.RaisePropertyChanged("Sent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SentDateTime {
            get {
                return this.SentDateTimeField;
            }
            set {
                if ((this.SentDateTimeField.Equals(value) != true)) {
                    this.SentDateTimeField = value;
                    this.RaisePropertyChanged("SentDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSErrors", Namespace="http://sms2.cdyne.com")]
    public enum SMSErrors : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STOPfromPhoneNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseKeyInvalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhoneNumberInvalid = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageInvalid = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledDateTimeIsNotUTC = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAssignedDID = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactCdyneAccountSuspended = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssignedDIDRequired = 10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSIncomingMessage", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSIncomingMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IncomingMessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid MatchedMessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseReceiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToPhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromPhoneNumber {
            get {
                return this.FromPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FromPhoneNumberField, value) != true)) {
                    this.FromPhoneNumberField = value;
                    this.RaisePropertyChanged("FromPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IncomingMessageID {
            get {
                return this.IncomingMessageIDField;
            }
            set {
                if ((this.IncomingMessageIDField.Equals(value) != true)) {
                    this.IncomingMessageIDField = value;
                    this.RaisePropertyChanged("IncomingMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MatchedMessageID {
            get {
                return this.MatchedMessageIDField;
            }
            set {
                if ((this.MatchedMessageIDField.Equals(value) != true)) {
                    this.MatchedMessageIDField = value;
                    this.RaisePropertyChanged("MatchedMessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseReceiveDate {
            get {
                return this.ResponseReceiveDateField;
            }
            set {
                if ((this.ResponseReceiveDateField.Equals(value) != true)) {
                    this.ResponseReceiveDateField = value;
                    this.RaisePropertyChanged("ResponseReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToPhoneNumber {
            get {
                return this.ToPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ToPhoneNumberField, value) != true)) {
                    this.ToPhoneNumberField = value;
                    this.RaisePropertyChanged("ToPhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSAdvancedRequest", Namespace="http://schemas.datacontract.org/2004/07/SmsWS")]
    [System.SerializableAttribute()]
    public partial class SMSAdvancedRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConcatenateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUnicodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LicenseKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.SMSRequest[] SMSRequestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Concatenate {
            get {
                return this.ConcatenateField;
            }
            set {
                if ((this.ConcatenateField.Equals(value) != true)) {
                    this.ConcatenateField = value;
                    this.RaisePropertyChanged("Concatenate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LicenseKey {
            get {
                return this.LicenseKeyField;
            }
            set {
                if ((this.LicenseKeyField.Equals(value) != true)) {
                    this.LicenseKeyField = value;
                    this.RaisePropertyChanged("LicenseKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.SMSRequest[] SMSRequests {
            get {
                return this.SMSRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSRequestsField, value) != true)) {
                    this.SMSRequestsField = value;
                    this.RaisePropertyChanged("SMSRequests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSRequest", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedDIDField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PhoneNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ScheduledDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusPostBackURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AssignedDID {
            get {
                return this.AssignedDIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedDIDField, value) != true)) {
                    this.AssignedDIDField = value;
                    this.RaisePropertyChanged("AssignedDID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PhoneNumbers {
            get {
                return this.PhoneNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumbersField, value) != true)) {
                    this.PhoneNumbersField = value;
                    this.RaisePropertyChanged("PhoneNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenceID {
            get {
                return this.ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceIDField, value) != true)) {
                    this.ReferenceIDField = value;
                    this.RaisePropertyChanged("ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime ScheduledDateTime {
            get {
                return this.ScheduledDateTimeField;
            }
            set {
                if ((this.ScheduledDateTimeField.Equals(value) != true)) {
                    this.ScheduledDateTimeField = value;
                    this.RaisePropertyChanged("ScheduledDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StatusPostBackURL {
            get {
                return this.StatusPostBackURLField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusPostBackURLField, value) != true)) {
                    this.StatusPostBackURLField = value;
                    this.RaisePropertyChanged("StatusPostBackURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSKeywordResponse", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSKeywordResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.SMSKeywordReturnCode ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.KeywordResponseInfo[] SMSKeywordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.SMSKeywordReturnCode ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.KeywordResponseInfo[] SMSKeyword {
            get {
                return this.SMSKeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSKeywordField, value) != true)) {
                    this.SMSKeywordField = value;
                    this.RaisePropertyChanged("SMSKeyword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSKeywordReturnCode", Namespace="http://sms2.cdyne.com")]
    public enum SMSKeywordReturnCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoError = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordAdded = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordAlreadyInUse = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShortCodeNotAssignedToKey = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LicenseKeyInvalid = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordInvalid = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ShortCodeInvalid = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordRemoved = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KeywordNotFound = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalError = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordResponseInfo", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class KeywordResponseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.SMSKeywordReturnCode ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDate {
            get {
                return this.EntryDateField;
            }
            set {
                if ((this.EntryDateField.Equals(value) != true)) {
                    this.EntryDateField = value;
                    this.RaisePropertyChanged("EntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.SMSKeywordReturnCode ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortCode {
            get {
                return this.ShortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodeField, value) != true)) {
                    this.ShortCodeField = value;
                    this.RaisePropertyChanged("ShortCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SMSKeywordRequest", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class SMSKeywordRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid LicenseKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChickenSoftware.Cdyne.KeywordRequestInfo[] SMSKeywordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid LicenseKey {
            get {
                return this.LicenseKeyField;
            }
            set {
                if ((this.LicenseKeyField.Equals(value) != true)) {
                    this.LicenseKeyField = value;
                    this.RaisePropertyChanged("LicenseKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChickenSoftware.Cdyne.KeywordRequestInfo[] SMSKeywords {
            get {
                return this.SMSKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSKeywordsField, value) != true)) {
                    this.SMSKeywordsField = value;
                    this.RaisePropertyChanged("SMSKeywords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeywordRequestInfo", Namespace="http://sms2.cdyne.com")]
    [System.SerializableAttribute()]
    public partial class KeywordRequestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeywordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keyword {
            get {
                return this.KeywordField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordField, value) != true)) {
                    this.KeywordField = value;
                    this.RaisePropertyChanged("Keyword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortCode {
            get {
                return this.ShortCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodeField, value) != true)) {
                    this.ShortCodeField = value;
                    this.RaisePropertyChanged("ShortCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms2.cdyne.com", ConfigurationName="ChickenSoftware.Cdyne.Isms")]
    public interface Isms {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendResponse")]
        ChickenSoftware.Cdyne.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> SimpleSMSsendAsync(string PhoneNumber, string Message, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostback", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostbackResponse")]
        ChickenSoftware.Cdyne.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostback", ReplyAction="http://sms2.cdyne.com/Isms/SimpleSMSsendWithPostbackResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> SimpleSMSsendWithPostbackAsync(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AdvancedSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/AdvancedSMSsendResponse")]
        ChickenSoftware.Cdyne.SMSResponse[] AdvancedSMSsend(ChickenSoftware.Cdyne.SMSAdvancedRequest AdvancedRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AdvancedSMSsend", ReplyAction="http://sms2.cdyne.com/Isms/AdvancedSMSsendResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse[]> AdvancedSMSsendAsync(ChickenSoftware.Cdyne.SMSAdvancedRequest AdvancedRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusWebPostResponse")]
        ChickenSoftware.Cdyne.SMSResponse GetMessageStatusWebPost(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusWebPostResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> GetMessageStatusWebPostAsync(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatus", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusResponse")]
        ChickenSoftware.Cdyne.SMSResponse GetMessageStatus(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatus", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> GetMessageStatusAsync(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceID", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceIDResponse")]
        ChickenSoftware.Cdyne.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceID", ReplyAction="http://sms2.cdyne.com/Isms/GetMessageStatusByReferenceIDResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse[]> GetMessageStatusByReferenceIDAsync(string ReferenceID, System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesWebPostResponse")]
        ChickenSoftware.Cdyne.SMSIncomingMessage[] GetUnreadIncomingMessagesWebPost(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesWebPostResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSIncomingMessage[]> GetUnreadIncomingMessagesWebPostAsync(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessages", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesResponse")]
        ChickenSoftware.Cdyne.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessages", ReplyAction="http://sms2.cdyne.com/Isms/GetUnreadIncomingMessagesResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSIncomingMessage[]> GetUnreadIncomingMessagesAsync(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessageWebPost", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageWebPostResponse")]
        bool CancelMessageWebPost(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessageWebPost", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageWebPostResponse")]
        System.Threading.Tasks.Task<bool> CancelMessageWebPostAsync(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessage", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageResponse")]
        bool CancelMessage(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/CancelMessage", ReplyAction="http://sms2.cdyne.com/Isms/CancelMessageResponse")]
        System.Threading.Tasks.Task<bool> CancelMessageAsync(System.Guid MessageID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetKeywordsWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetKeywordsWebPostResponse")]
        ChickenSoftware.Cdyne.SMSKeywordResponse GetKeywordsWebPost(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetKeywordsWebPost", ReplyAction="http://sms2.cdyne.com/Isms/GetKeywordsWebPostResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> GetKeywordsWebPostAsync(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetKeywords", ReplyAction="http://sms2.cdyne.com/Isms/GetKeywordsResponse")]
        ChickenSoftware.Cdyne.SMSKeywordResponse GetKeywords(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/GetKeywords", ReplyAction="http://sms2.cdyne.com/Isms/GetKeywordsResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> GetKeywordsAsync(System.Guid LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AssignKeyword", ReplyAction="http://sms2.cdyne.com/Isms/AssignKeywordResponse")]
        ChickenSoftware.Cdyne.SMSKeywordResponse AssignKeyword(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/AssignKeyword", ReplyAction="http://sms2.cdyne.com/Isms/AssignKeywordResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> AssignKeywordAsync(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/RemoveKeyword", ReplyAction="http://sms2.cdyne.com/Isms/RemoveKeywordResponse")]
        ChickenSoftware.Cdyne.SMSKeywordResponse RemoveKeyword(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms2.cdyne.com/Isms/RemoveKeyword", ReplyAction="http://sms2.cdyne.com/Isms/RemoveKeywordResponse")]
        System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> RemoveKeywordAsync(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsmsChannel : ChickenSoftware.Cdyne.Isms, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsmsClient : System.ServiceModel.ClientBase<ChickenSoftware.Cdyne.Isms>, ChickenSoftware.Cdyne.Isms {
        
        public IsmsClient() {
        }
        
        public IsmsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsmsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsmsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChickenSoftware.Cdyne.SMSResponse SimpleSMSsend(string PhoneNumber, string Message, System.Guid LicenseKey) {
            return base.Channel.SimpleSMSsend(PhoneNumber, Message, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> SimpleSMSsendAsync(string PhoneNumber, string Message, System.Guid LicenseKey) {
            return base.Channel.SimpleSMSsendAsync(PhoneNumber, Message, LicenseKey);
        }
        
        public ChickenSoftware.Cdyne.SMSResponse SimpleSMSsendWithPostback(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL) {
            return base.Channel.SimpleSMSsendWithPostback(PhoneNumber, Message, LicenseKey, StatusPostBackURL);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> SimpleSMSsendWithPostbackAsync(string PhoneNumber, string Message, System.Guid LicenseKey, string StatusPostBackURL) {
            return base.Channel.SimpleSMSsendWithPostbackAsync(PhoneNumber, Message, LicenseKey, StatusPostBackURL);
        }
        
        public ChickenSoftware.Cdyne.SMSResponse[] AdvancedSMSsend(ChickenSoftware.Cdyne.SMSAdvancedRequest AdvancedRequest) {
            return base.Channel.AdvancedSMSsend(AdvancedRequest);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse[]> AdvancedSMSsendAsync(ChickenSoftware.Cdyne.SMSAdvancedRequest AdvancedRequest) {
            return base.Channel.AdvancedSMSsendAsync(AdvancedRequest);
        }
        
        public ChickenSoftware.Cdyne.SMSResponse GetMessageStatusWebPost(System.Guid MessageID) {
            return base.Channel.GetMessageStatusWebPost(MessageID);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> GetMessageStatusWebPostAsync(System.Guid MessageID) {
            return base.Channel.GetMessageStatusWebPostAsync(MessageID);
        }
        
        public ChickenSoftware.Cdyne.SMSResponse GetMessageStatus(System.Guid MessageID) {
            return base.Channel.GetMessageStatus(MessageID);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse> GetMessageStatusAsync(System.Guid MessageID) {
            return base.Channel.GetMessageStatusAsync(MessageID);
        }
        
        public ChickenSoftware.Cdyne.SMSResponse[] GetMessageStatusByReferenceID(string ReferenceID, System.Guid LicenseKey) {
            return base.Channel.GetMessageStatusByReferenceID(ReferenceID, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSResponse[]> GetMessageStatusByReferenceIDAsync(string ReferenceID, System.Guid LicenseKey) {
            return base.Channel.GetMessageStatusByReferenceIDAsync(ReferenceID, LicenseKey);
        }
        
        public ChickenSoftware.Cdyne.SMSIncomingMessage[] GetUnreadIncomingMessagesWebPost(System.Guid LicenseKey) {
            return base.Channel.GetUnreadIncomingMessagesWebPost(LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSIncomingMessage[]> GetUnreadIncomingMessagesWebPostAsync(System.Guid LicenseKey) {
            return base.Channel.GetUnreadIncomingMessagesWebPostAsync(LicenseKey);
        }
        
        public ChickenSoftware.Cdyne.SMSIncomingMessage[] GetUnreadIncomingMessages(System.Guid LicenseKey) {
            return base.Channel.GetUnreadIncomingMessages(LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSIncomingMessage[]> GetUnreadIncomingMessagesAsync(System.Guid LicenseKey) {
            return base.Channel.GetUnreadIncomingMessagesAsync(LicenseKey);
        }
        
        public bool CancelMessageWebPost(System.Guid MessageID) {
            return base.Channel.CancelMessageWebPost(MessageID);
        }
        
        public System.Threading.Tasks.Task<bool> CancelMessageWebPostAsync(System.Guid MessageID) {
            return base.Channel.CancelMessageWebPostAsync(MessageID);
        }
        
        public bool CancelMessage(System.Guid MessageID) {
            return base.Channel.CancelMessage(MessageID);
        }
        
        public System.Threading.Tasks.Task<bool> CancelMessageAsync(System.Guid MessageID) {
            return base.Channel.CancelMessageAsync(MessageID);
        }
        
        public ChickenSoftware.Cdyne.SMSKeywordResponse GetKeywordsWebPost(System.Guid LicenseKey) {
            return base.Channel.GetKeywordsWebPost(LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> GetKeywordsWebPostAsync(System.Guid LicenseKey) {
            return base.Channel.GetKeywordsWebPostAsync(LicenseKey);
        }
        
        public ChickenSoftware.Cdyne.SMSKeywordResponse GetKeywords(System.Guid LicenseKey) {
            return base.Channel.GetKeywords(LicenseKey);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> GetKeywordsAsync(System.Guid LicenseKey) {
            return base.Channel.GetKeywordsAsync(LicenseKey);
        }
        
        public ChickenSoftware.Cdyne.SMSKeywordResponse AssignKeyword(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest) {
            return base.Channel.AssignKeyword(KeywordRequest);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> AssignKeywordAsync(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest) {
            return base.Channel.AssignKeywordAsync(KeywordRequest);
        }
        
        public ChickenSoftware.Cdyne.SMSKeywordResponse RemoveKeyword(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest) {
            return base.Channel.RemoveKeyword(KeywordRequest);
        }
        
        public System.Threading.Tasks.Task<ChickenSoftware.Cdyne.SMSKeywordResponse> RemoveKeywordAsync(ChickenSoftware.Cdyne.SMSKeywordRequest KeywordRequest) {
            return base.Channel.RemoveKeywordAsync(KeywordRequest);
        }
    }
}
